# Generated by Django 5.0.6 on 2024-05-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/image')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='цена продажи')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='дата последнего изменения')),
                ('views_counter', models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='количество просмотров')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'category', 'purchase_price'],
            },
        ),
    ]
