# Generated by Django 5.0.6 on 2024-06-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'category', 'purchase_price'], 'permissions': [('can_unpublish_product', 'Можно отменить публикацию продукта'), ('can_change_description', 'Можно изменить описание продукта'), ('can_change_category', 'Можно изменить категорию товара')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
