# Generated by Django 5.0.6 on 2024-06-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_options_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'category', 'purchase_price'], 'permissions': [('can_unpublish_product', 'Можно отменить публикацию продукта'), ('can_edit_product_description', 'Можно редактировать описание продукта'), ('can_edit_product_category', 'Можно редактировать категорию товара')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
